### ISSUE TITLE
Error database connection and migration Prisma step during install

### ISSUE THREAD

**Issue by pgregorynz** [aaronpowell/azure-remix-stack#1]
@aaronpowell having issues getting past the DB connection and migration.

Im using sqlexpress and when it asks for the local connection string I am using the following:

sqlserver://localhost\sql2019;initialCatalog=remixAzure;integratedSecurity=true;trustServerCertificate=true;

Hoever I get the following error every time.  I have tried with SA password as well.  Is there something that I am doing wrong?

Error: Migration engine error:
Error creating a database connection.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remixAzure-180a@ setup:db: `prisma migrate dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remixAzure-180a@ setup:db script.

**Comment by aaronpowell** [comment]
My guess is that it's the Prisma driver not supporting sqlexpress, it's not on their listed support - https://www.prisma.io/docs/reference/database-reference/supported-databases and while I know there's a lot of overlaps between the two, there might be some underlying differences in the way it establishes a connection that makes it incompatible.

Is there a reason to now install a local SQL server or use the [Docker version](https://docs.microsoft.com/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-bash&WT.mc_id=javascript-0000-aapowell) of SQL Server?

**Comment by pgregorynz** [comment]
We also tried full blown SQL on our dev server with the same result.

Super keen to ge this up and running, glad that someone created the stack.

**Comment by aaronpowell** [comment]
Is that with ldap security to access the remote SQL server or a username/password combo?

**Comment by aaronpowell** [comment]
Closing as this is related to the legacy Stack template, the new one doesn't use MSSQL
