### ISSUE TITLE
remix v2.2.0 - nginx landing page

### ISSUE THREAD

**Issue by starkajs** [aaronpowell/azure-remix-stack#14]
Hi,

When using the template with the latest version of remix (2.2.0) and then updating the Dockerfile to node:19-alpine the deployment just stays on the nginx landing page. 

I'm not sure where to debug from there if you can point that out it'd be a great help? We're using Azure through foundershub so would prefer to stay with Azure which is made easier with your template (thank you!!) but still challenging!

Andrew

**Comment by aaronpowell** [comment]
Within Azure Container Apps (where it deploys to) you'll find options for **Revisions** and **Containers**:

![Options in the Azure Portal](https://github.com/aaronpowell/azure-remix-stack/assets/434140/a82d0eae-957a-42ac-b473-b5914e75c685)

Under **Revisions** you can find what the status of the deployment is, here's an example:

![Example revision details](https://github.com/aaronpowell/azure-remix-stack/assets/434140/6a06205d-2790-437b-af3e-aa1f06213f06)

Clicking on the name will give you links to the various logs in which you could dig more into it, but it sounds like the deployment didn't work, so you might need to look into the `azd` logs locally first.

**Comment by starkajs** [comment]
Thanks Aaron. You've just made the start of my day an amazing one as going into the logs allowed me to see that "chalk" wasn't in package.json.

Thanks again
Andrew

**Comment by starkajs** [comment]
No longer an issue

**Comment by aaronpowell** [comment]
Can you send a PR with the updated Dockerfile? Should probably bump the one in the template, and that way you get the contributor credits 😄

**Comment by starkajs** [comment]
Will attempt to work out how to do that today :-)
