### ISSUE TITLE
Required upgrade of msw to avoid error with recent node versions

### ISSUE THREAD

**Issue by vanakenm** [aaronpowell/azure-remix-stack#5]
First thanks a lot for this! I'm not in prod yet, but looking really great so far.

I've followed the Remix tutorial steps with the azure stack. I could not start my server:

```
npm run dev
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /home/martin/code/beeo/beeoutstanding-remix/node_modules/headers-polyfill/package.json
```

After some tests I find that the "root culprit" was the [msw](https://www.npmjs.com/package/msw) package. Upgrading from 0.39 to 0.47 (latest) made it work with npm v17

I can provide a (one line) PR if interested.

**Comment by aaronpowell** [comment]
Closing as this is related to the legacy Stack.
